version: 2

updates:
  - directory: "/"
    package-ecosystem: "docker"
    schedule:
      interval: "weekly"
  - directory: "/"
    package-ecosystem: "pip"
    schedule:
      interval: "weekly"
  - directory: "/server"
    package-ecosystem: "docker"
    schedule:
      interval: "weekly"
