version: 2

updates:
  - directory: "/"
    package-ecosystem: "pip"
    schedule:
      interval: "weekly"
    groups:
       poetry-dependencies:
          applies-to: version-updates
          patterns:
            - "*"
          exclude-patterns:
            - "poetry"
