[tool.poetry]
name = "manim-website-api"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "manim_website_api"}]

[tool.poetry.dependencies]
python = "^3.8"
feedparser = "^6.0"
flask = "^2.1"
requests = "^2"
python-dotenv = "^0.20"
flask-cors = "^3.0"
google-api-python-client = "^2.70"
gunicorn = "^20.0.4"
uvicorn = {version = "^0.18.3"}
Flask-SQLAlchemy = "^2.5.1"
PyMySQL = "^1.0.2"
ipdb = "^0.13.9"
cryptography = "^38.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
