[tool.poetry]
name = "manim-website-api"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
flask = "^2.2"
python-dotenv = "^0.21"
flask-cors = "^4.0"
certifi = "*"
sqlalchemy = "^1.4.25"
Flask-SQLAlchemy = "^3.0.5"
PyMySQL = "^1.0.2"
cryptography = "^41.0.1" # needed by PyMySQL

[tool.poetry.group.updator.dependencies]
requests = "^2"
feedparser = "^6.0"
google-api-python-client = "^2.51"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
ipdb = "^0.13.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
