[tool.poetry]
name = "manim-website-api"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "manim_website_api"}]

[tool.poetry.dependencies]
python = "^3.8"
feedparser = "^6.0"
flask = "^2.1"
requests = "^2"
supabase = "^0.5"
python-dotenv = "^0.20"
flask-cors = "^3.0"
google-api-python-client = "^2.51"
gunicorn = "^20.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
