name: Deply Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    if: (github.repository == 'ManimCommunity/manim-website-api' && github.event_name == 'push' && github.ref == 'refs/heads/main')

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64,linux/amd64
          push: true
          file: Dockerfile
          tags: |
            ghcr.io/manimcommunity/manim-website-api:latest
